import os
import sys
import shutil
import glob
from typing import Callable, Iterator
import json
import pyarrow
from datetime import timedelta, date
import numpy as np
import pandas as pd
import dask
import dask.dataframe as dd
import pandas_read_xml as pdx
from pandas_read_xml import auto_separate_tables


save_path = './downloads/us'
backup_path = './backup/us'
temp_path = './temp/us'
data_path = './data/us'
upload_folder_path = './upload/us'

link_base = 'https://bulkdata.uspto.gov/data/trademark/dailyxml/applications/'
root_key_list = ['trademark-applications-daily', 'application-information', 'file-segments', 'action-keys']
key_columns = ['action-key', 'case-file|serial-number']


# -------------------------------------------------------------------------------------
# These functions will help download all the files and save them locally.
# -------------------------------------------------------------------------------------


def daterange(start_date: date, end_date: date) -> Iterator:
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)


def get_historical_zip_file_path_list() -> list:
    zip_name_base = 'apc18840407-20191231'
    return [f"{link_base}{zip_name_base}-{str(i).rjust(2, '0')}.zip"
            for i in range(1,66)]


def get_daily_zip_file_path(for_date: str) -> str:
    zip_name_base = 'apc'
    return f"{link_base}{zip_name_base}{for_date.strftime('%y%m%d')}.zip"


def get_daily_zip_file_path_list() -> list:
    start_date = date(2020, 1, 1)
    end_date = date.today() - timedelta(days=1)
    return [get_daily_zip_file_path(_date)
            for _date in daterange(start_date, end_date)]


def convert_date_columns(df: pd.DataFrame) -> pd.DataFrame:
    return (df.apply(lambda column:
                     pd.to_datetime(column, format='%Y%m%d', errors='coerce')
                     if 'date' in column.name
                     else column))


def convert_boolean_columns(df: pd.DataFrame) -> pd.DataFrame:
    return (df.apply(lambda column:
                     column.fillna(False).replace('F', False).replace('T', True)
                     if column.name.endswith('-in')
                     else column))


def clean(df: pd.DataFrame) -> pd.DataFrame:
    return (df
            .pipe(convert_boolean_columns)
            .pipe(convert_date_columns))


def clean_all_tables(data: dict) -> dict:
    return {table_name: clean(table_data)
            for table_name, table_data in data.items()}


def save_all_tables(data: dict, path: str, folder_name: str) -> None:
    if not os.path.exists(f'{path}/{folder_name}'):
        os.makedirs(f'{path}/{folder_name}')
    for key in data:
        data[key].to_parquet(f'{path}/{folder_name}/{key}.parquet', index=False)


# This function is the high-level wrapper for the download process.


def download_all() -> None:
    for zip_file in get_historical_zip_file_path_list() + get_daily_zip_file_path_list():
        zip_name = os.path.basename(zip_file).replace('.zip', '')
        if not os.path.exists(f'{save_path}/{zip_name}'):
            try:
                print(f'Downloading: {zip_name}')
                save_all_tables(
                    clean_all_tables(
                        pdx.read_xml(zip_file, root_key_list)
                        .pipe(auto_separate_tables, key_columns)
                    ),
                    save_path,
                    zip_name
                )
            except Exception as error:
                print(f'Failed to download: {zip_name}')
                raise error


# -------------------------------------------------------------------------------------
# These functions will help read the downloaded files and combine them.
# -------------------------------------------------------------------------------------


def get_historical_download_folder_list() -> list:
    name_base = 'apc18840407-20191231'
    return [f"{save_path}/{name_base}-{str(i).rjust(2, '0')}"
            for i in range(1,66)]


def get_daily_download_folder_list() -> list:
    name_base = 'apc'
    start_date = date(2020, 1, 1)
    end_date = date.today() - timedelta(days=1)
    return [f"{save_path}/{name_base}{_date.strftime('%y%m%d')}"
            for _date in daterange(start_date, end_date)]


def get_files_in_folder(folder: str, file_extension: str) -> list:
    return glob.glob(f"{folder}/*.{file_extension}")


def get_subfolders(folder: str) -> list:
    return [f.name for f in os.scandir(folder) if f.is_dir()]


def remove_unnecessary(df: dd.DataFrame) -> dd.DataFrame:
    return (df
            .loc[:, df.columns != 'action-key']
            .drop_duplicates())


def removed_keys_from_one_dataframe_in_another(remove_from_df: pd.DataFrame,
                                               keys_in_df: dd.DataFrame) -> pd.DataFrame:
    return (remove_from_df
            .loc[~remove_from_df['serial-number'].isin(keys_in_df['serial-number'].unique()), :])


def removed_keys_from_one_dataframe_in_another_dask(remove_from_df: dd.DataFrame,
                                                    keys_in_df: dd.DataFrame) -> dd.DataFrame:
    return (remove_from_df
            .map_partitions(
                removed_keys_from_one_dataframe_in_another,
                keys_in_df=keys_in_df
            ))


def delete_then_append_dataframe(old_df: dd.DataFrame,
                                 new_df: dd.DataFrame) -> dd.DataFrame:
    return removed_keys_from_one_dataframe_in_another_dask(old_df, new_df).append(new_df)


def save(df: dd.DataFrame, path: str) -> None:
    (df
     .map_partitions(clean)
     .to_parquet(path,
                 engine='pyarrow',
                 compression='snappy',
                 allow_truncated_timestamps=True))


# These functions make the individual updates happen in a "safer" way by saving to temp folder and replacing the old data only after success.

def backup() -> None:
    if os.path.exists(backup_path):
        shutil.rmtree(backup_path)
    shutil.copytree(data_path, backup_path)


def commit(update_version: str) -> None:
    shutil.rmtree(data_path)
    shutil.copytree(temp_path, data_path)
    write_latest_folder_name(update_version)
    shutil.rmtree(temp_path)


def rollback() -> None:
    shutil.rmtree(data_path)
    shutil.copytree(backup_path, data_path)
    shutil.rmtree(backup_path)


def get_next_folder_name() -> str:
    if os.path.exists(f'{data_path}/updates.json'):
        with open(f'{data_path}/updates.json', 'r') as jf:
            latest = json.loads(jf.read())['latest']
        download_folder_list = get_historical_download_folder_list() + get_daily_download_folder_list()
        index = download_folder_list.index(latest)
        if index < len(download_folder_list) - 1:
            return download_folder_list[index+1]
        else:
            return None
    else:
        return f'{save_path}/apc18840407-20191231-01'


def write_latest_folder_name(update_version: str) -> None:
    with open(f'{data_path}/updates.json', 'w') as jf:
        json.dump({'latest': update_version}, jf)


# This function is the high-level wrap for the merging process.

def update_file(file_path: str) -> None:
    table_name = os.path.basename(file_path).replace('.parquet', '')
    print(f'    {table_name}')
    temp_file_path = f'{temp_path}/{table_name}'
    target_file_path = f'{data_path}/{table_name}'
    if os.path.exists(target_file_path):
        (delete_then_append_dataframe(dd.read_parquet(target_file_path),
                                      dd.read_parquet(file_path).pipe(remove_unnecessary))
        .pipe(save, temp_file_path))
    else:
        (dd.read_parquet(file_path).pipe(remove_unnecessary)
        .pipe(save, temp_file_path))


# This is an extra function to combine the parquet files into one file each.

def make_each_table_as_single_file() -> None:
    tables = get_subfolders(data_path)
    for table in tables:
        print(f'    {table}')
        try:
            (dd.read_parquet(f'{data_path}/{table}')
             .compute()
             .to_parquet(f'{upload_folder_path}/{table}.parquet',
                         engine='pyarrow',
                         compression='snappy',
                         allow_truncated_timestamps=True,
                         index=False))
        except Exception as error:
            print('    Failed.')
            raise error


# This is an optional function to repartition the parquet files using the single files. Use with caution.
def repartition_data() -> None:
    """
    Make sure you already have an up-to-date /upload/us/ folder with .parquet files
    Delete all but the updates.json in the /data/us/ folder
    Then run this function by using a python environment within your markstat folder:

    ```python
    from markstattools import us
    us.repartition_data()
    ```
    """
    tables = get_files_in_folder(upload_folder_path, 'parquet')
    for table in tables:
        table_name = os.path.basename(table).replace('.parquet', '')
        print(table_name)
        (dd.read_parquet(table)
         .repartition(partition_size="500MB")
         .to_parquet(f'{data_path}/{table_name}',
                     engine='pyarrow',
                     compression='snappy',
                     allow_truncated_timestamps=True))


# -------------------------------------------------------------------------------------
# This function will automate everything.
# -------------------------------------------------------------------------------------


def update_all() -> None:
    download_all()
    update_version = get_next_folder_name()
    updated = False
    while update_version:
        print("Backing up.")
        backup()
        try:
            print(f"Merging in: {update_version}")
            for parquet_file in get_files_in_folder(update_version, 'parquet'):
                update_file(parquet_file)
            print("Committing changes.")
            commit(update_version)
            update_version = get_next_folder_name()
            updated = True
        except:
            print("Failed. Rolling back.")
            rollback()
            update_version = None
        print('Preparing upload files')
    if updated:
        make_each_table_as_single_file()
    print("Done")


def initialise():
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    if not os.path.exists(temp_path):
        os.makedirs(temp_path)
    if not os.path.exists(upload_folder_path):
        os.makedirs(upload_folder_path)
    if not os.path.exists(data_path):
        os.makedirs(data_path)
        codes = dd.from_pandas(pd.DataFrame(data={
            'table_name': [
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "madrid-international-filing-requests",
                "prior-registration-applications",
                "prior-registration-applications",
                "prior-registration-applications",
                "prior-registration-applications",
                "international-registration",
                "international-registration",
                "international-registration",
                "international-registration",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-statements",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-owners",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "case-file-header",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications",
                "classifications"
            ],
            'column_name': [
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "madrid-international-filing-record|international-status-code",
                "prior-registration-application|relationship-type",
                "prior-registration-application|relationship-type",
                "prior-registration-application|relationship-type",
                "prior-registration-application|relationship-type",
                "international-status-code",
                "international-status-code",
                "international-status-code",
                "international-status-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-statement|type-code",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|party-type",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "case-file-owner|legal-entity-type-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "cancellation-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "law-office-assigned-location-code",
                "mark-drawing-code",
                "mark-drawing-code",
                "mark-drawing-code",
                "mark-drawing-code",
                "mark-drawing-code",
                "mark-drawing-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "status-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|international-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|status-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code",
                "classification|us-code"
            ],
            'code': [
                "400",
                "401",
                "402",
                "403",
                "404",
                "405",
                "406",
                "407",
                "408",
                "480",
                "498",
                "499",
                "0",
                "1",
                "2",
                "3",
                "100",
                "101",
                "102",
                "1",
                "AF",
                "A0",
                "B0",
                "CC",
                "CD",
                "CS",
                "CU",
                "DM",
                "D0",
                "D1",
                "FN",
                "GS",
                "IN",
                "LS",
                "MD",
                "MK",
                "NR",
                "N0",
                "OR",
                "PM",
                "TF",
                "TR",
                "TLIT",
                "TNSF",
                "LINKBR",
                "10",
                "11",
                "13",
                "15",
                "17",
                "18",
                "19",
                "20",
                "21",
                "23",
                "25",
                "27",
                "28",
                "29",
                "30",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56",
                "57",
                "58",
                "59",
                "60",
                "61",
                "62",
                "63",
                "64",
                "65",
                "66",
                "67",
                "68",
                "69",
                "70",
                "71",
                "72",
                "73",
                "74",
                "75",
                "76",
                "77",
                "78",
                "79",
                "80",
                "81",
                "82",
                "83",
                "84",
                "85",
                "86",
                "87",
                "88",
                "89",
                "90",
                "91",
                "92",
                "93",
                "94",
                "95",
                "96",
                "97",
                "98",
                "99",
                " ",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "A",
                "B",
                "C",
                "D",
                "E",
                "510",
                "520",
                "530",
                "540",
                "550",
                "560",
                "570",
                "580",
                "590",
                "970",
                "980",
                "G00",
                "G10",
                "G20",
                "G30",
                "G40",
                "G50",
                "G60",
                "G70",
                "G80",
                "J00",
                "J10",
                "J20",
                "J30",
                "J40",
                "J50",
                "J60",
                "J70",
                "J80",
                "L00",
                "L10",
                "L20",
                "L30",
                "L40",
                "L50",
                "L60",
                "L70",
                "L80",
                "L90",
                "M10",
                "M20",
                "M30",
                "M40",
                "M50",
                "M60",
                "M70",
                "M80",
                "M90",
                "N10",
                "N20",
                "N30",
                "N40",
                "N50",
                "N60",
                "N70",
                "N80",
                "N90",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "0",
                "400",
                "401",
                "402",
                "403",
                "404",
                "405",
                "406",
                "410",
                "411",
                "412",
                "413",
                "414",
                "415",
                "416",
                "417",
                "600",
                "601",
                "602",
                "603",
                "604",
                "605",
                "606",
                "607",
                "608",
                "609",
                "612",
                "614",
                "616",
                "618",
                "620",
                "622",
                "624",
                "625",
                "626",
                "630",
                "631",
                "632",
                "638",
                "640",
                "641",
                "642",
                "643",
                "644",
                "645",
                "646",
                "647",
                "648",
                "649",
                "650",
                "651",
                "652",
                "653",
                "654",
                "655",
                "656",
                "657",
                "658",
                "659",
                "660",
                "661",
                "663",
                "664",
                "665",
                "666",
                "667",
                "668",
                "672",
                "680",
                "681",
                "682",
                "686",
                "688",
                "689",
                "690",
                "692",
                "693",
                "694",
                "700",
                "701",
                "702",
                "703",
                "704",
                "705",
                "706",
                "707",
                "708",
                "709",
                "710",
                "711",
                "712",
                "713",
                "714",
                "715",
                "717",
                "718",
                "719",
                "720",
                "721",
                "722",
                "724",
                "725",
                "730",
                "731",
                "732",
                "733",
                "734",
                "739",
                "740",
                "744",
                "745",
                "746",
                "748",
                "752",
                "753",
                "756",
                "757",
                "760",
                "762",
                "763",
                "764",
                "765",
                "766",
                "771",
                "772",
                "773",
                "774",
                "775",
                "777",
                "778",
                "779",
                "780",
                "790",
                "794",
                "800",
                "801",
                "802",
                "803",
                "804",
                "806",
                "807",
                "808",
                "809",
                "810",
                "811",
                "812",
                "813",
                "814",
                "815",
                "816",
                "817",
                "818",
                "819",
                "820",
                "821",
                "822",
                "823",
                "824",
                "825",
                "900",
                "901",
                "969",
                "970",
                "973",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "200",
                "201",
                "202",
                "1",
                "A",
                "2",
                "B",
                "3",
                "C",
                "4",
                "D",
                "5",
                "E",
                "6",
                "7",
                "8",
                "9",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "100",
                "101",
                "102",
                "103",
                "104",
                "105",
                "106",
                "107",
                "200",
                "201",
                "202",
                "A",
                "B"
            ],
            'description': [
                "APPLICATION FOR INTL REGISTRATION AUTOMATICALLY CERTIFIED",
                "MANUAL CERTIFICATION REQUIRED BY MPU",
                "APPLICATION FOR INTERNATIONAL REGISTRATION NOT PAID",
                "APPLICATION FOR INTERNATIONAL REGISTRATION MANUALLY CERTIFIED",
                "CERTIFICATION REJECTED BY MPU",
                "APPLICATION FOR INTERNATIONAL REGISTRATION SENT TO IB",
                "IRREGULARITY RECEIVED FROM IB (RESPONSE NOT REQUIRED)",
                "RESPONSE TO IRREGULARITY RECEIVED FROM APPLICANT",
                "IRREGULARITY RECEIVED FROM IB (RESPONSE REQUIRED)",
                "APPLICATION FOR IR REGISTERED BY IB",
                "ABANDONED - NO RESPONSE TO IRREGULARITY",
                "DEATH OF INTERNATIONAL REGISTRATION",
                "Prior Registration",
                "Continuity Parent",
                "Continuity Child",
                "Non Registration Document Control Number",
                "IR cancelled as result of change in IR number",
                "IR cancelled",
                "Death of IR",
                "Request for extension of protection established",
                "In Another Form Statement",
                "Amendment to a Registration/Renewal Certificate",
                "Certificate of Correction for Registration",
                "Indication of Colors claimed",
                "Description of the Colors Claimed",
                "Certification Mark Statement",
                "Concurrent Use Statement",
                "Description of Mark",
                "Disclaimer",
                "Disclaimer with Predetermined Text",
                "Foreign Registration Data",
                "Goods and Services",
                "Interference Statement",
                "Lining/Stippling Statement",
                "Undefined Application/Registration",
                "Mark Overflow",
                "Non Registration Information",
                "Name/Portrait Description and/or Consent Statement",
                "Order restricting Scope or Claim of Registration",
                "Pseudo Mark",
                "Section 2(f) Limitation Statement",
                "Translation of Words in Mark",
                "Transliteration Statement",
                "Transformation Information",
                "Linkage Information",
                "Original Applicant",
                "1st New Owner Before Publication",
                "2nd New Owner Before Publication",
                "3rd New Owner Before Publication",
                "4th New Owner Before Publication",
                "5th New Owner Before Publication",
                "6th New Owner Before Publication",
                "Owner at Publication",
                "1st New Owner After Publication",
                "2nd New Owner After Publication",
                "3rd New Owner After Publication",
                "4th New Owner After Publication",
                "5th New Owner After Publication",
                "6th New Owner After Publication",
                "Original Registrant",
                "1st New Owner Entered After Registration",
                "2nd New Owner Entered After Registration",
                "3rd New Owner Entered After Registration",
                "4th New Owner Entered After Registration",
                "5th New Owner Entered After Registration",
                "6th New Owner Entered After Registration",
                "7th New Owner Entered After Registration",
                "8th New Owner Entered After Registration",
                "9th New Owner Entered After Registration",
                "10th New Owner Entered After Registration",
                "Individual",
                "Partnership",
                "Corporation",
                "Joint Ownership",
                "Joint Venture",
                "Association Incorporated",
                "Association Unincorporated",
                "Trustee",
                "Joint Stock Company",
                "Limited Liability Joint Stock",
                "Company",
                "Foundation",
                "Limited Partnership",
                "State Agency",
                "Federal Agency",
                "Limited Liability Company",
                "Trust",
                "Estate",
                "Sole Proprietorship",
                "Limited Liability Limited Partnership",
                "Limited Liability Partnership",
                "Limited Corporation",
                "Partnership Limited By Shares",
                "Private Limited Company",
                "Aktiengesellschaft (AG)",
                "Besloten Vennootschap (B.V.)",
                "Gesellschaft Mit Beschränkter Haftung (GMBH)",
                "Gmbh & Co. Kg",
                "Kabushiki Kaisha (K.K.)",
                "Kommanditgesellschaft (KG)",
                "Kommanditgesellschaft Auf Aktien (KGAA)",
                "Naamloze Vennootschap (NV)",
                "Société Anonyme (SA)",
                "Société Par Actions Simplifiée (SAS)",
                "Società Per Azioni (SPA)",
                "Agency Of The United States Government",
                "Body Politic And Corporate",
                "Business Trust",
                "Charitable Corporation",
                "Charitable Trust",
                "Charitable, Non-Profit Corporation",
                "Chartered Bank",
                "Congressionally Chartered Nonprofit Organization",
                "Cooperative Association",
                "Cooperative Corporation",
                "Credit Union",
                "Federally Chartered Credit Union",
                "Federally-Recognized Indian Tribe",
                "Instrumentality",
                "Municipal Corporation",
                "National Banking Association",
                "Non-Profit Association",
                "Non-Profit Corporation",
                "Non-Profit Organization",
                "Non-Stock Corporation",
                "Professional Corporation",
                "Public Benefit Corporation",
                "State-Recognized Indian Tribe",
                "State University",
                "Stock Company",
                "Tax Exempt Corporation",
                "Allmennaksjeselskap (ASA)",
                "Aktiebolag",
                "Aktieselskab",
                "Anpartsselskab (APS)",
                "Asociación Civil",
                "Besloten Vennootschap Met Beperkte Aansprakelijkheid (BVBA)",
                "Commanditaire Vennootschap (C.V.)",
                "Compania Anonima",
                "Eingetragener Verein",
                "Exempted Limited Partnership (ELP)",
                "Fondazion",
                "Genossenschaft (GEN)",
                "Gesellschaft Burgerlichen Rechts",
                "Julkinen Osakeyhtiö",
                "Private Company Limited By Shares",
                "Private Limited Liability Company",
                "Private Unlimited Company",
                "Professional Limited Liability Company",
                "Proprietary Company",
                "Proprietary Limited Company",
                "Public Company Limited By Shares",
                "Public Limited Company",
                "Sociedad Anonima",
                "Sociedad Anónima Inscrita De Capital Abierto (S.A.I.C.A.)",
                "Sociedad De Responsabilidad Limitada",
                "Sociedade Por Ações (S.A.)",
                "Société En Commandite",
                "Societa Cooperativa (SC)",
                "Société En Nom Collectif",
                "Societá In Accomandita Semplice (SAS)",
                "Società Semplice (SS)",
                "Societas Europae (SE)",
                "Société Coopérative (SCOP)",
                "Société En Commandite Par Actions (SCA)",
                "Société En Commandite (SC)",
                "Unknown",
                "Other",
                "None",
                "None",
                "Section 7(d) Entire Registration",
                "Section 8 - Entire Registration",
                "Section 18 - Entire Registration",
                "Section 24 - Entire Registration",
                "Section 37 - Entire Registration",
                "Entire Registration inadvertently Issued",
                "Inadvertently issued-entire Registration restored to pendency",
                "Section 7 (d) - Class(es) in multiple class Registration",
                "Section 8 - Class(es) in multiple class Registration",
                "Section 18 - Class(es) in multiple class  Registration",
                "Section 24 - Class(es) in multiple class Registration",
                "Section 37 - Class(es) in multiple class Registration",
                "LAW OFFICE 1",
                "LAW OFFICE 2",
                "LAW OFFICE 3",
                "LAW OFFICE 4",
                "LAW OFFICE 5",
                "LAW OFFICE 6",
                "LAW OFFICE 7",
                "LAW OFFICE 8",
                "LAW OFFICE 9",
                "ADP TEST GROUP B",
                "ATM DIRECTOR'S STAFF",
                "GROUP B DIRECTOR",
                "LAW OFFICE 9",
                "LAW OFFICE 10",
                "LAW OFFICE 11",
                "LAW OFFICE 12",
                "LAW OFFICE 13",
                "LAW OFFICE 14",
                "LAW OFFICE 15",
                "LAW OFFICE 16",
                "GROUP A DIRECTOR",
                "LAW OFFICE 1",
                "LAW OFFICE 2",
                "LAW OFFICE 3",
                "LAW OFFICE 4",
                "LAW OFFICE 5",
                "LAW OFFICE 6",
                "LAW OFFICE 7",
                "LAW OFFICE 8",
                "GROUP A DIRECTOR",
                "LAW OFFICE 101",
                "LAW OFFICE 102",
                "LAW OFFICE 103",
                "LAW OFFICE 104",
                "LAW OFFICE 105",
                "LAW OFFICE 106",
                "LAW OFFICE 107",
                "LAW OFFICE 108",
                "LAW OFFICE 109",
                "LAW OFFICE 110",
                "LAW OFFICE 111",
                "LAW OFFICE 112",
                "LAW OFFICE 113",
                "LAW OFFICE 114",
                "LAW OFFICE 115",
                "LAW OFFICE 116",
                "LAW OFFICE 117",
                "LAW OFFICE 118",
                "LAW OFFICE 119",
                "LAW OFFICE 120",
                "LAW OFFICE 121",
                "LAW OFFICE 122",
                "LAW OFFICE 123",
                "LAW OFFICE 124",
                "LAW OFFICE 125",
                "LAW OFFICE 126",
                "LAW OFFICE 127",
                "Typeset: Word(s)/letter(s)/number(s)",
                "Illustration: Drawing or design without any word(s)/letter(s)/number(s)",
                "Illustration: Drawing or design which also includes word(s)/letter(s)/number(s)",
                "Standard character mark",
                "Illustration: Drawing with word(s)/letter(s)/number(s) in Stylized form",
                "Where no drawing is possible such as for sound",
                "Indifferent - UNKNOWN",
                "Dead/Cancelled - IR CANCELLED; APPLICATION PENDING TRANSFORMATION",
                "Dead/Cancelled - IR CANCELLED - NO TRANSFORMATION FILED",
                "Dead/Abandoned - IR CANCELLED; US APPLICATION ABANDONED",
                "Dead/Cancelled - IR CANCELLED; REGISTRATION PENDING TRANSFORMATION",
                "Dead/Cancelled - IR CANCELLED; US REGISTRATION CANCELLED",
                "Dead/Cancelled - IR CANCELED; APPLICATION TRANSFRMED",
                "Dead/Cancelled - IR CANCELLED; REGISTRATION TRANSFORMED",
                "Live/Pending - IR RESTRICTED; US APP.  ABANDONED, PENDING TRANSFORMATION",
                "Dead/Abandoned - IR RESTRICTED; US APP. ABANDONED; NO TRANSFORMATION FILED",
                "Dead/Abandoned - IR RESTRICTED; US APPLICATION ABANDONED",
                "Live/Pending - IR RESTRICTED; US REG. CANCELLED PEND TRANSFORMATION",
                "Dead/Cancelled - IR RESTRICTED; US REG. CANCELLED; NO TRANSFORMATION FILED",
                "Dead/Cancelled - IR RESTRICTED; US REGISTRATION CANCELLED",
                "Dead/Abandoned - IR RESTRICTED; US APP ABANDONED; US APP TRANSFORMED",
                "Dead/Cancelled - IR RESTRICTED; US REG CANCELLED; US REG TRANSFORMED",
                "Dead/Abandoned - ABANDONED - INCOMPLETE RESPONSE",
                "Dead/Abandoned - ABANDONED - EXPRESS",
                "Dead/Abandoned - ABANDONED - FAILURE TO RESPOND OR LATE RESPONSE",
                "Dead/Abandoned - ABANDONED - AFTER EX PARTE APPEAL",
                "Dead/Abandoned - ABANDONED - AFTER INTER-PARTES DECISION",
                "Dead/Abandoned - ABANDONED - EXPRESS AFTER PUB",
                "Dead/Abandoned - ABANDONED - NO STATEMENT OF USE FILED",
                "Dead/Abandoned - ABANDONED - DEFECTIVE STATEMENT OF USE",
                "Dead/Abandoned - ABANDONED - AFTER PETITION DECISION",
                "Dead/Abandoned - ABANDONED - DEFECTIVE DIVIDED APPLICATION",
                "Dead/Abandoned - PETITION TO REVIVE-RECEIVED",
                "Dead/Abandoned - ABANDONED PETITION TO REVIVE-DENIED",
                "Live/Pending - REVIVED - AWAITING FURTHER ACTION",
                "Dead/Abandoned - ABANDONED FILE - BACKFILE",
                "Live/Pending - BACKFILE APPLICATION ADDED TO DATA BASE - STATUS NOT RECORDED",
                "Indifferent - MISASSIGNED SERIAL NUMBER",
                "Live/Registered - REGISTERED - BACKFILE",
                "Live/Registered - REGISTRATION ADDED TO THE DATA BASE-STATUS UNCLEAR",
                "Dead/Cancelled - REGISTERED - BACKFILE CANCELLED OR EXPIRED",
                "Live/Pending - NEW APPLICATION - RECORD INITIALIZED NOT ASSIGNED TO EXAMINER",
                "Live/Pending - NEW APPLICATION - DIVIDED - INITIAL PROCESSING",
                "Dead - INFORMAL APPLICATION",
                "Live/Pending - NEW APPLICATION - ASSIGNED TO EXAMINER",
                "Live/Pending - NON-FINAL ACTION COUNTED - NOT MAILED",
                "Live/Pending - NON-FINAL ACTION - MAILED",
                "Live/Pending - INVENTORIED AS REJECTED",
                "Live/Pending - PREVIOUS ACTION/ALLOWANCE COUNT WITHDRAWN",
                "Live/Pending - FINAL REFUSAL COUNTED - NOT MAILED",
                "Live/Pending - FINAL REFUSAL - MAILED",
                "Live/Pending - EXAMINERS AMENDMENT COUNTED - NOT MAILED",
                "Live/Pending - EXAMINERS AMENDMENT - MAILED",
                "Live/Pending - ACTION CONTINUING FINAL COUNTED - NOT MAILED",
                "Live/Pending - ACTION CONTINUING FINAL - MAILED",
                "Live/Pending - SUSPENSION INQUIRY COUNTED - NOT MAILED",
                "Live/Pending - SUSPENSION INQUIRY - MAILED",
                "Live/Pending - SUSPENSION LETTER COUNTED - NOT MAILED",
                "Live/Pending - SUSPENSION LETTER - MAILED",
                "Live/Pending - REPORT COMPLETED SUSPENSION CHECK - CASE STILL SUSPENDED",
                "Live/Pending - EXAMINERS AMENDMENT/PRIORITY ACTION COUNTED NOT MAILED",
                "Live/Pending - EXAMINERS AMENDMENT/PRIORITY ACTION MAILED",
                "Live/Pending - PRIORITY ACTION COUNTED NOT MAILED",
                "Live/Pending - PRIORITY ACTION MAILED",
                "Live/Pending - SUBSEQUENT FINAL REFUSAL COUNTED NOT MAILED",
                "Live/Pending - SUBSEQUENT FINAL MAILED",
                "Live/Pending - RESPONSE AFTER NON-FINAL ACTION - ENTERED",
                "Live/Pending - RESPONSE AFTER FINAL REJECTION - ENTERED",
                "Live/Pending - INVENTORIED AS AMENDED",
                "Live/Pending - NOTICE OF UNRESPONSIVE AMENDMENT - COUNTED",
                "Live/Pending - NOTICE OF UNRESPONSIVE AMENDMENT - MAILED",
                "Live/Pending - REFUSAL WITHDRAWL LETTER - COUNTED",
                "Live/Pending - REFUSAL WITHDRAWL LETTER - MAILED",
                "Live/Pending - REINSTATED - AWAITING FURTHER ACTION",
                "Live/Pending - APPROVED FOR PUBLICATION",
                "Live/Pending - PUBLICATION/ISSUE REVIEW COMPLETE",
                "Live/Pending - ADDITIONAL REVIEW COMPLETED – RETURNED TO PUB CYCLE",
                "Live/Pending - PUBLISHED FOR OPPOSITION",
                "Live/Pending - NOTICE OF ALLOWANCE - ISSUED",
                "Live/Pending - NOTICE OF ALLOWANCE - WITHDRAWN",
                "Live/Pending - NOTICE OF ALLOWANCE - CANCELLED",
                "Live/Pending - WITHDRAWN BEFORE PUBLICATION",
                "Live/Pending - WITHDRAWN FROM ISSUE-JURISDICTION RESTORED",
                "Live/Pending - WITHDRAWN BEFORE ISSUE",
                "Live/Registered - REGISTERED",
                "Live/Registered - SECTION 8-ACCEPTED",
                "Live/Registered - SECTION 8 & 15-ACCEPTED AND ACKNOWLEDGED",
                "Live/Registered - SECTION 15-ACKNOWLEDGED",
                "Live/Registered - PARTIAL SECTION 8 ACCEPTED",
                "Live/Registered - PARTIAL SECTION 8 & 15 ACCEPTED AND ACKNOWLEDGED",
                "Live/Registered - SECTION 71 ACCEPTED",
                "Live/Registered - PARTIAL SECTION 71 ACCEPTED",
                "Live/Registered - PARTIAL SECTION 71 & 15 ACCEPTED AND ACKNOWLEDGED",
                "Dead/Cancelled - CANCELLED – SECTION 71",
                "Dead/Cancelled - CANCELLED - SECTION 8",
                "Dead/Cancelled - CANCELLED - SECTION 7",
                "Dead/Cancelled - CANCELLED BY COURT ORDER (SECTION 37)",
                "Dead/Cancelled - CANCELLED - SECTION 18",
                "Dead/Cancelled - CANCELLED - SECTION 24",
                "Indifferent/Cancelled - CANCELLED - RESTORED TO PENDENCY",
                "Live - REGISTERED - AWAITING DIVISIONAL FEE",
                "Live/Pending - REQUEST FOR FIRST EXTENSION - FILED",
                "Live/Pending - REQUEST FOR SECOND EXTENSION - FILED",
                "Live/Pending - REQUEST FOR THIRD EXTENSION - FILED",
                "Live/Pending - REQUEST FOR FOURTH EXTENSION - FILED",
                "Live/Pending - REQUEST FOR FIFTH EXTENSION - FILED",
                "Live/Pending - EXTENSION REQUEST REFUSAL - COUNTED",
                "Live/Pending - EXTENSION REQUEST REFUSAL - MAILED",
                "Live/Pending - FIRST EXTENSION - GRANTED",
                "Live/Pending - SECOND EXTENSION - GRANTED",
                "Live/Pending - THIRD EXTENSION - GRANTED",
                "Live/Pending - FOURTH EXTENSION - GRANTED",
                "Live/Pending - FIFTH EXTENSION - GRANTED",
                "Live/Registered - Section 71 & 15 – ACCEPTED AND ACKNOWLEDGED",
                "Live/Pending - POST REGISTRATION PAPER FILED - ASSIGNED TO PARA-LEGAL",
                "Live/Pending - STATEMENT OF USE - FILED",
                "Live/Pending - STATEMENT OF USE - INFORMAL-LETTER MAILED",
                "Live/Pending - STATEMENT OF USE - INFORMAL-RESPONSE ENTERED",
                "Live/Pending - STATEMENT OF USE - TO EXAMINER",
                "Live/Pending - SU - EXAMINER STATEMENT COUNTED - NOT MAILED",
                "Live/Pending - SU - EXAMINER STATEMENT - MAILED",
                "Live/Pending - EXAMINER STATEMENT COUNTED - NOT MAILED",
                "Live/Pending - EXAMINER STATEMENT - MAILED",
                "Live/Pending - EX PARTE APPEAL PENDING",
                "Live/Pending - EX PARTE APPEAL TERMINATED",
                "Live/Pending - EX PARTE APPEAL-REFUSAL AFFIRMED",
                "Live/Pending - EX PARTE APPEAL DISMISSED AS MOOT",
                "Live/Pending - CONCURRENT USE PROCEEDING TERMINATED-GRANTED",
                "Live/Pending - CONCURRENT USE PROCEEDING TERMINATED-DENIED",
                "Live/Pending - CONCURRENT USE PROCEEDING PENDING",
                "Live/Pending - INTERFERENCE PROCEEDING PENDING",
                "Live/Pending - EXTENSION OF TIME TO OPPOSE PROCESS - TERMINATED",
                "Live/Pending - OPPOSITION PENDING",
                "Live/Pending - OPPOSITION DISMISSED",
                "Live/Pending - OPPOSITION TERMINATED-SEE TTAB RECORDS",
                "Live/Registered - CANCELLATION DISMISSED",
                "Live/Pending - OPPOSITION SUSTAINED",
                "Live/Registered - CANCELLATION TERMINATED - SEE TTAB RECORDS",
                "Live/Registered - CANCELLATION PENDING",
                "Live/Pending - JURISDICTION RESTORED TO EXAMINING ATTORNEY",
                "Live/Registered - REGISTERED AND RENEWED",
                "Live/Pending - OPPOSITION PAPERS FILED",
                "Live/Pending - REQUEST FOR EXTENSION OF TIME TO FILE OPPOSITION",
                "Live/Pending - AMENDMENT AFTER PUBLICATION",
                "Live/Pending - APPEAL RECEIVED AT TTAB",
                "Live/Pending - SU - NON-FINAL ACTION COUNTED - NOT MAILED",
                "Live/Pending - SU - NON-FINAL ACTION - MAILED",
                "Live/Pending - SU - FINAL REFUSAL COUNTED - NOT MAILED",
                "Live/Pending - SU - FINAL REFUSAL - MAILED",
                "Live/Pending - SU - EXAMINERS AMENDMENT COUNTED - NOT MAILED",
                "Live/Pending - SU - EXAMINERS AMENDMENT - MAILED",
                "Live/Pending - SU - ACTION CONTINUING FINAL COUNTED - NOT MAILED",
                "Live/Pending - SU - ACTION CONTINUING FINAL - MAILED",
                "Live/Pending - SU - RESPONSE AFTER NON-FINAL ACTION - ENTERED",
                "Live/Pending - SU - RESPONSE AFTER FINAL REJECTION - ENTERED",
                "Live/Pending - SU - NOTICE OF UNRESPONSIVE AMENDMENT - COUNTED",
                "Live/Pending - SU - NOTICE OF UNRESPONSIVE AMENDMENT - MAILED",
                "Live/Pending - SU - STATEMENT OF USE ACCEPTED - APPROVED FOR REGISTRATION",
                "Live/Pending - SU - REGISTRATION REVIEW COMPLETE",
                "Live/Pending - SU - EXAMINERS AMENDMENT/PRIORITY ACTION COUNTED NOT MAILED",
                "Live/Pending - SU - EXAMINERS AMENDMENT/PRIORITY ACTION MAILED",
                "Live/Pending - SU - PRIORITY ACTION COUNTED NOT MAILED",
                "Live/Pending - SU - PRIORITY ACTION MAILED",
                "Live/Pending - SU - SUBSEQUENT FINAL REFUSAL WRITTEN",
                "Live/Pending - SU - SUBSEQUENT FINAL MAILED",
                "Dead/Expired - EXPIRED",
                "Dead - DEAD INVENTORIED AS REJECTED",
                "Live/Pending - NON REGISTRATION DATA",
                "Indifferent - RECORD CREATED DUE TO ASSIGNMENT REQUEST",
                "Live/Pending - PENDING PETITION/COURT DECISION",
                "Chemicals",
                "Paints",
                "Cosmetics and Cleaning Preparations",
                "Lubricants and Fuels",
                "Pharmaceuticals",
                "Metal Goods",
                "Machinery",
                "Hand Tools",
                "Electrical and Scientific Apparatus",
                "Medical Apparatus",
                "Environmental Control Apparatus",
                "Vehicles",
                "Firearms",
                "Jewelry",
                "Musical Instruments",
                "Paper Goods and Printed Matter",
                "Rubber Goods",
                "Leather Goods",
                "Non-metallic Building Materials",
                "Furniture and Articles Not Otherwise Classified",
                "Housewares and Glass",
                "Cordage and Fibers",
                "Yarns and Threads",
                "Fabrics",
                "Clothing",
                "Fancy Goods",
                "Floor Coverings",
                "Toys and Sporting Goods",
                "Meats and Processed Foods",
                "Staple Foods",
                "Natural Agricultural Products",
                "Light Beverages",
                "Wines and Spirits",
                "Smokers Articles",
                "Advertising and Business",
                "Insurance and Financial",
                "Construction and Repair",
                "Communication",
                "Transportation and Storage",
                "Material Treatment",
                "Education and Entertainment",
                "Scientific computer and legal services",
                "Hotel and restaurant services",
                "Medical beauty and agricultural services",
                "Personal services",
                "COLLECTIVE MEMBERSHIP",
                "GOODS",
                "SERVICES",
                "Sec. 7(d) – Entire Registration",
                "Sec. 7(d) – Class(es) in a Multiple Class Registration",
                "Sec. 8 – Entire Registration",
                "Sec. 8 – Class(es) in a Multiple Class registration",
                "Sec. 18 – Entire Registration",
                "Sec. 18 – Class(es) in a Multiple Class Registration",
                "Sec. 24 – Entire Registration",
                "Sec. 24 – Class(es) in a Multiple Class Registration",
                "Sec. 37 – Entire Registration",
                "Sec. 37 – Class(es) in a Multiple Class Registration",
                "Active",
                "Inactive – Insufficient fee received",
                "Abandoned",
                "Expired",
                "Raw or Partly Prepared Materials",
                "Receptacles",
                "Baggage Animal Equipments Portfolios and Pocket Books",
                "Abrasives and Polishing Materials",
                "Adhesives",
                "Chemicals and Chemical Compositions",
                "Cordage",
                "Smokers Articles not Including Tobacco Products",
                "Explosives Firearms Equipments and Projectiles",
                "Fertilizers",
                "Inks and Inking Materials",
                "Construction Materials",
                "Hardware and Plumbing and Steamfitting Supplies",
                "Metals and Metal Castings and Forgings",
                "Oils and Greases",
                "Protective and Decorative Coatings",
                "Tobacco Products",
                "Medicines and Pharmaceutical Preparations",
                "Vehicles",
                "Linoleum and Oiled Cloth",
                "Electrical Appratus Machines and Supplies",
                "Games Toys and Sporting Goods",
                "Cutlery Machinery and Tools and Parts Thereof",
                "Laundry Appliances and Machines",
                "Locks and Safes",
                "Measuring and Scientific Appliances",
                "Horological Instruments",
                "Jewelry and Precious-metal Ware",
                "Brooms Brushes and Dusters",
                "Crockery Earthenware and Porcelain",
                "Filters and Refrigerators",
                "Furniture and Upholstery",
                "Glassware",
                "Heating Lighting and Ventilating Apparatus",
                "Belting Hose Machinery Packing and Nonmetallic Tires",
                "Musical Instruments and Supplies",
                "Paper and Stationery",
                "Prints and Publications",
                "Clothing",
                "Fancy Goods Furnishings and Notions",
                "Canes Parasols and Umbrellas",
                "Knitted Netted and Textile Fabrics and Substitutes Therefor",
                "Thread and Yarn",
                "Dental Medical and Surgical Appliances",
                "Soft Drinks and Carbonated Waters",
                "Foods and Ingredients of Foods",
                "Wines",
                "Malt Beverages and Liquors",
                "Distilled Alcoholic Liquors",
                "Merchandise Not Otherwise Classified",
                "Cosmetics and Toilet Preparations",
                "Detergents and Soaps",
                "Miscellaneous",
                "Advertising and Business",
                "Insurance and Financial",
                "Construction and Repair",
                "Communication",
                "Transportation and Storage",
                "Material Treatment",
                "Education and Entertainment",
                "Collective Membership",
                "Goods",
                "Services",
                "Goods",
                "Services"
            ]
        }), npartitions=1)
        codes.to_parquet(f'{data_path}/codes', engine='pyarrow', compression='snappy')


if __name__ == '__main__':
    initialise()
    update_all()
